parameters:
    phobetor_billomat.handler: PhobetorBillomatBundle\Services\BillomatHandler

services:
  phobetor_billomat:
    class: %phobetor_billomat.handler%
    arguments: [%phobetor_billomat.id%,%phobetor_billomat.api_key%,%phobetor_billomat.application.id%,%phobetor_billomat.application.secret%,%phobetor_billomat.wait_for_rate_limit_reset%,%phobetor_billomat.async%]
