parameters:
    phobetor_billomat.handler: PhobetorBillomatBundle\Services\BillomatHandler

services:
  phobetor_billomat:
    class: %phobetor_billomat.handler%
    arguments:
      - %phobetor_billomat.clients%
